name: flutter_ai_toolkit_example
description: >-
  Sample apps showing off various features of the Flutter AI Toolkit.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: '>=3.27.0-0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
    - assets/halloween-bg.png
